# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QpI_uSJf5F792t0k_XNfXlz2fBm1kgaO
"""

import pandas as pd

df = pd.read_csv('Cars Datasets 2025.csv', encoding='latin-1')

df

from matplotlib import pyplot as plt
_df_43['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

df2 = pd.read_csv('/content/Hearing.csv')

df2

from matplotlib import pyplot as plt
df2['Belief_Early_Hearing_Care'].plot(kind='hist', bins=20, title='Belief_Early_Hearing_Care')
plt.gca().spines[['top', 'right',]].set_visible(False)

df3 = pd.read_csv("/content/Electric_Vehicle_Population_Data.csv")

df3

from matplotlib import pyplot as plt
df3.plot(kind='scatter', x='Model Year', y='Electric Range', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)