# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wCVpGL4zvQv9vFp6Wyw6lAuzTGhqmSO0
"""

from google.colab import files
import pandas as pd

#Subir archivo desde tu PC (te pedirá seleccionarlo)
uploaded = files.upload()

#Luego lo cargas en un DataFrame
df = pd.read_csv("migrations_metadata.csv")  # ajusta el nombre exacto

#Ver primeras filas
df.head()

#Ver información general
df.info()

# 3 Gráficas esenciales para datos de migración
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Configurar el estilo
plt.style.use('default')
sns.set_palette("husl")

# 1. GRÁFICA DE BARRAS - Top 10 Repositorios más migrados
print("=== GRÁFICA 1: Top 10 Repositorios más Migrados ===")
plt.figure(figsize=(12, 6))

top_repos = df['repo'].value_counts().head(10)
plt.bar(range(len(top_repos)), top_repos.values, color='skyblue', edgecolor='black')
plt.title('Top 10 Repositorios más Migrados', fontsize=16, fontweight='bold')
plt.xlabel('Repositorios')
plt.ylabel('Número de Migraciones')
plt.xticks(range(len(top_repos)), top_repos.index, rotation=45, ha='right')
plt.grid(axis='y', alpha=0.3)

# Agregar valores en las barras
for i, v in enumerate(top_repos.values):
    plt.text(i, v + 0.5, str(v), ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.show()

# 2. GRÁFICA DE PIE - Top 8 Usuarios más activos
print("\n=== GRÁFICA 2: Top 8 Usuarios más Activos ===")
plt.figure(figsize=(10, 8))

top_users = df['user'].value_counts().head(8)
colors = ['#ff9999','#66b3ff','#99ff99','#ffcc99','#ff99cc','#c2c2f0','#ffb3e6','#c4e17f']

plt.pie(top_users.values, labels=top_users.index, autopct='%1.1f%%',
        startangle=90, colors=colors, shadow=True)
plt.title('Top 8 Usuarios más Activos', fontsize=16, fontweight='bold')
plt.axis('equal')
plt.show()

# 3. HISTOGRAMA - Distribución de tipos de datos de columnas
print("\n=== GRÁFICA 3: Distribución de Tipos de Datos ===")
plt.figure(figsize=(12, 6))

col_types = df['column_data_type'].value_counts().head(12)
plt.bar(range(len(col_types)), col_types.values, color='lightcoral', edgecolor='black')
plt.title('Distribución de Tipos de Datos de Columnas', fontsize=16, fontweight='bold')
plt.xlabel('Tipos de Datos')
plt.ylabel('Frecuencia')
plt.xticks(range(len(col_types)), col_types.index, rotation=45, ha='right')
plt.grid(axis='y', alpha=0.3)

# Agregar valores en las barras
for i, v in enumerate(col_types.values):
    plt.text(i, v + 0.5, str(v), ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.show()

# RESUMEN RÁPIDO
print("\n" + "="*40)
print("📊 RESUMEN RÁPIDO")
print("="*40)
print(f"Total registros: {len(df):,}")
print(f"Repositorios únicos: {df['repo'].nunique()}")
print(f"Usuarios únicos: {df['user'].nunique()}")
print(f"Tipos de datos únicos: {df['column_data_type'].nunique()}")